name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build the OHCI Image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      image-tag: ${{ steps.output-image-tag.outputs.image-tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Output image tag
        id: output-image-tag
        # Set the image tag, same used by the isle-gradle-docker-plugin
        run: echo ::set-output name=image-tag::$(git describe --tags --always --first-parent)
        
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: BuildX
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.2
        with:
          push: true
          tags: |
            jhu-idc/drupal/drupal-init-mariadb:latest
            jhu-idc/drupal/drupal-init-mariadb:${{ steps.output-image-tag.outputs.image-tag}}
          
